version: "3.9"  # optional since v1.27.0
services:
  server:
    image: digikam-utils-server:latest
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ${DIGIKAM_DB_FOLDER_PATH}
        target: /digikam/db
      - type: bind
        source: ${DIGIKAM_ALBUM_FOLDER_PATH}
        target: /digikam/album
      - type: bind
        source: ${SERVER_CODE_FOLDER_PATH}
        target: /app
      - type: bind
        source: ${INTERNAL_DB_PATH}
        target: /db
    environment:
      - INTERNAL_DIGIKAM_DB_PATH=/digikam/db/digikam4.db
      - INTERNAL_DIGIKAM_ALBUM_FOLDER=/digikam/album
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
  ui:
    image: digikam-utils-ui:latest
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ${UI_CODE_FOLDER_PATH}
        target: /app
